spring.application.name=autorizacion
server.port=${PORT:9000}
app.oauth.issuer=${OAUTH_ISSUER:http://localhost:9000}
app.oauth.secret=${OAUTH_CLIENT_SECRET:operador-local}
app.oauth.lector-secret=${OAUTH_READER_SECRET:lector-local}
management.endpoints.web.exposure.include=health
