spring.application.name=banco-xyz-batch
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/banco_xyz}
spring.datasource.username=${DB_USER:banco}
spring.datasource.password=${DB_PASSWORD:banco123}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.batch.jdbc.initialize-schema=always
spring.sql.init.mode=always
spring.batch.job.name=${BATCH_JOB:transaccionesJob}

app.archivos.transacciones=${TRANSACCIONES_FILE:classpath:data/transacciones.csv}
app.archivos.intereses=${INTERESES_FILE:classpath:data/intereses.csv}
app.archivos.cuentas-anuales=${CUENTAS_ANUALES_FILE:classpath:data/cuentas_anuales.csv}
app.reportes.directorio=build/reportes

logging.level.org.springframework.batch=INFO
