spring.main.web-application-type=servlet
server.port=${PORT:8082}
spring.batch.job.enabled=false
spring.artemis.mode=native
spring.artemis.broker-url=${JMS_URL:tcp://mensajeria:61616}
spring.artemis.user=${JMS_USER:app}
spring.artemis.password=${JMS_PASSWORD}
spring.jms.listener.concurrency=1
spring.jms.listener.max-concurrency=1
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
