CREATE TABLE IF NOT EXISTS solicitudes (
    id VARCHAR(36) PRIMARY KEY,
    proceso VARCHAR(40) NOT NULL,
    propietario VARCHAR(100) NOT NULL,
    estado VARCHAR(20) NOT NULL,
    creada TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
