CREATE TABLE IF NOT EXISTS transacciones_procesadas (
    id BIGINT PRIMARY KEY,
    fecha DATE NOT NULL,
    monto NUMERIC(18, 2) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    anomalia BOOLEAN NOT NULL,
    CONSTRAINT uk_transaccion_logica UNIQUE (fecha, monto, tipo)
);

CREATE TABLE IF NOT EXISTS resumen_transacciones (
    tipo VARCHAR(20) PRIMARY KEY,
    cantidad BIGINT NOT NULL,
    monto_total NUMERIC(18, 2) NOT NULL,
    anomalias BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS intereses_calculados (
    cuenta_id BIGINT PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    saldo_inicial NUMERIC(18, 2) NOT NULL,
    edad INTEGER NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    tasa NUMERIC(8, 6) NOT NULL,
    interes NUMERIC(18, 2) NOT NULL,
    saldo_final NUMERIC(18, 2) NOT NULL,
    CONSTRAINT uk_interes_logico UNIQUE (nombre, saldo_inicial, edad, tipo)
);

CREATE TABLE IF NOT EXISTS movimientos_anuales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id BIGINT NOT NULL,
    fecha DATE NOT NULL,
    transaccion VARCHAR(20) NOT NULL,
    monto NUMERIC(18, 2) NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    CONSTRAINT uk_movimiento_logico UNIQUE (cuenta_id, fecha, transaccion, monto, descripcion)
);

CREATE TABLE IF NOT EXISTS estados_cuenta_anuales (
    cuenta_id BIGINT NOT NULL,
    anio INTEGER NOT NULL,
    cantidad_movimientos BIGINT NOT NULL,
    total_depositos NUMERIC(18, 2) NOT NULL,
    total_cargos NUMERIC(18, 2) NOT NULL,
    saldo_anual NUMERIC(18, 2) NOT NULL,
    PRIMARY KEY (cuenta_id, anio)
);

CREATE TABLE IF NOT EXISTS registros_rechazados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job VARCHAR(80) NOT NULL,
    etapa VARCHAR(30) NOT NULL,
    datos VARCHAR(1000) NOT NULL,
    motivo VARCHAR(500) NOT NULL,
    fecha_rechazo TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
